import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import type { Database } from '@/integrations/supabase/types';
import { useAuth } from './useAuth';

type Requisicao = Database['public']['Tables']['requisicoes']['Row'] & {
  solicitante?: Database['public']['Tables']['profiles']['Row'];
  departamento?: Database['public']['Tables']['departamentos']['Row'];
  fornecedor_sugerido?: Database['public']['Tables']['fornecedores']['Row'];
  aprovador?: Database['public']['Tables']['profiles']['Row'];
  itens?: Database['public']['Tables']['itens_requisicao']['Row'][];
};

type ItemRequisicao = Database['public']['Tables']['itens_requisicao']['Row'];
type Departamento = Database['public']['Tables']['departamentos']['Row'];
type Fornecedor = Database['public']['Tables']['fornecedores']['Row'];

export function useRequisicoes() {
  const { user, profile } = useAuth();
  const [requisicoes, setRequisicoes] = useState<Requisicao[]>([]);
  const [departamentos, setDepartamentos] = useState<Departamento[]>([]);
  const [fornecedores, setFornecedores] = useState<Fornecedor[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user) {
      fetchRequisicoes();
      fetchDepartamentos();
      fetchFornecedores();
    }
  }, [user]);

  const fetchRequisicoes = async () => {
    try {
      const { data, error } = await supabase
        .from('requisicoes')
        .select(`
          *,
          solicitante:profiles!requisicoes_solicitante_id_fkey(nome, email),
          departamento:departamentos(nome),
          fornecedor_sugerido:fornecedores(nome),
          aprovador:profiles!requisicoes_aprovador_id_fkey(nome, email),
          itens:itens_requisicao(*)
        `)
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Error fetching requisicoes:', error);
      } else {
        setRequisicoes((data as any) || []);
      }
    } catch (error) {
      console.error('Error:', error);
    } finally {
      setLoading(false);
    }
  };

  const fetchDepartamentos = async () => {
    try {
      const { data, error } = await supabase
        .from('departamentos')
        .select('*')
        .order('nome');

      if (error) {
        console.error('Error fetching departamentos:', error);
      } else {
        setDepartamentos(data || []);
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };

  const fetchFornecedores = async () => {
    try {
      const { data, error } = await supabase
        .from('fornecedores')
        .select('*')
        .eq('ativo', true)
        .order('nome');

      if (error) {
        console.error('Error fetching fornecedores:', error);
      } else {
        setFornecedores(data || []);
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };

  const createRequisicao = async (
    requisicaoData: {
      departamento_id: string;
      fornecedor_sugerido_id?: string;
      justificativa: string;
    },
    itens: Omit<ItemRequisicao, 'id' | 'requisicao_id' | 'created_at' | 'preco_total'>[]
  ) => {
    if (!user) return { error: new Error('User not authenticated') };

    try {
      // Create requisition
      const { data: requisicao, error: reqError } = await supabase
        .from('requisicoes')
        .insert({
          ...requisicaoData,
          solicitante_id: profile?.id || '',
          codigo: '', // Will be generated by trigger
        })
        .select()
        .single();

      if (reqError) throw reqError;

      // Create items
      if (itens.length > 0) {
        const { error: itemsError } = await supabase
          .from('itens_requisicao')
          .insert(
            itens.map(item => ({
              ...item,
              requisicao_id: requisicao.id,
              preco_total: item.quantidade * item.preco_unitario,
            }))
          );

        if (itemsError) throw itemsError;
      }

      await fetchRequisicoes();
      return { data: requisicao, error: null };
    } catch (error) {
      console.error('Error creating requisicao:', error);
      return { data: null, error };
    }
  };

  const updateRequisicao = async (
    id: string,
    updates: Partial<Requisicao>,
    itens?: Omit<ItemRequisicao, 'id' | 'requisicao_id' | 'created_at' | 'preco_total'>[]
  ) => {
    try {
      // Update requisition
      const { data, error: updateError } = await supabase
        .from('requisicoes')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (updateError) throw updateError;

      // Update items if provided
      if (itens) {
        // Delete existing items
        await supabase
          .from('itens_requisicao')
          .delete()
          .eq('requisicao_id', id);

        // Insert new items
        if (itens.length > 0) {
          await supabase
            .from('itens_requisicao')
            .insert(
              itens.map(item => ({
                ...item,
                requisicao_id: id,
                preco_total: item.quantidade * item.preco_unitario,
              }))
            );
        }
      }

      await fetchRequisicoes();
      return { data, error: null };
    } catch (error) {
      console.error('Error updating requisicao:', error);
      return { data: null, error };
    }
  };

  const aprovarRequisicao = async (id: string, observacoes?: string) => {
    if (!user) return { error: new Error('User not authenticated') };

    return updateRequisicao(id, {
      status: 'aprovada',
      aprovador_id: profile?.id,
      data_aprovacao: new Date().toISOString(),
      observacoes_aprovador: observacoes,
    });
  };

  const rejeitarRequisicao = async (id: string, observacoes: string) => {
    if (!user) return { error: new Error('User not authenticated') };

    return updateRequisicao(id, {
      status: 'rejeitada',
      aprovador_id: profile?.id,
      data_aprovacao: new Date().toISOString(),
      observacoes_aprovador: observacoes,
    });
  };

  const enviarParaAprovacao = async (id: string) => {
    return updateRequisicao(id, {
      status: 'pendente',
    });
  };

  // Computed values
  const minhasRequisicoes = requisicoes.filter(req => req.solicitante_id === profile?.id);
  const requisicoesParaAprovar = requisicoes.filter(
    req => req.status === 'pendente' && (profile?.role === 'aprovador' || profile?.role === 'admin')
  );
  const requisicoesAprovadas = requisicoes.filter(req => req.status === 'aprovada');
  const requisicoesPendentes = requisicoes.filter(req => req.status === 'pendente');
  const rascunhos = requisicoes.filter(req => req.status === 'rascunho' && req.solicitante_id === profile?.id);

  // Statistics
  const stats = {
    total: requisicoes.length,
    pendentes: requisicoesPendentes.length,
    aprovadas: requisicoesAprovadas.length,
    valorTotal: requisicoesAprovadas.reduce((sum, req) => sum + req.valor_total, 0),
  };

  return {
    requisicoes,
    minhasRequisicoes,
    requisicoesParaAprovar,
    requisicoesAprovadas,
    requisicoesPendentes,
    rascunhos,
    departamentos,
    fornecedores,
    stats,
    loading,
    createRequisicao,
    updateRequisicao,
    aprovarRequisicao,
    rejeitarRequisicao,
    enviarParaAprovacao,
    refetch: fetchRequisicoes,
  };
}