// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrcxhghpoandppvgsovn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yY3hoZ2hwb2FuZHBwdmdzb3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDAyNTgsImV4cCI6MjA3MjQ3NjI1OH0.1EG4uAYO8FY_RGv2S3yGfQOxR0bfsxjPq5poDFUs8dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});